services:
  backend:
    image: ghcr.io/patryk-bernasiewicz/gjk-backend:${APP_VERSION}-PROD
    pull_policy: always
    ports:
      - '3220:3220'
    environment:
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3220/api/v1/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  dashboard:
    image: ghcr.io/patryk-bernasiewicz/gjk-dashboard:${APP_VERSION}-PROD
    pull_policy: always
    ports:
      - '3223:3223'
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3223']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
