packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - browser-tabs-lock
  - core-js
  - esbuild
  - prisma
