services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3220:3220'
    environment:
      NODE_ENV: production
      PORT: 3220
      ALLOWED_ORIGINS: 'https://yourdomain.com,https://app.yourdomain.com'
      CLERK_PUBLISHABLE_KEY: 'pk_live_your_prod_key_here'
    secrets:
      - GJK_PROD_DATABASE_URL
      - GJK_PROD_CLERK_SECRET_KEY
    entrypoint:
      - sh
      - -c
      - |
        export DATABASE_URL=$$(cat /run/secrets/GJK_PROD_DATABASE_URL) && \
        export CLERK_SECRET_KEY=$$(cat /run/secrets/GJK_PROD_CLERK_SECRET_KEY) && \
        node dist/main
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          'require("http").get("http://localhost:3220/api/health", (res) => process.exit(res.statusCode === 200 ? 0 : 1))',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

secrets:
  GJK_PROD_CLERK_SECRET_KEY:
    external: true
  GJK_PROD_DATABASE_URL:
    external: true
